PE1-oob.lab.local:
- name: FastEthernet2/0
  ip: 10.1.11.1/31
  enable: True
- name: Ethernet5/0
  ip: 172.16.254.1/24
  enable: True
- name: Ethernet6/1
  enable: True
- name: Loopback0
  ip: 10.255.255.11/32
  enable: True
PE2-oob.lab.local:
- name: FastEthernet2/0
  ip: 10.2.12.1/31
  enable: True
- name: Ethernet6/2
  enable: True
- name: Loopback0
  ip: 10.255.255.12/32
  enable: True
CE1-oob.lab.local:
- name: Ethernet1/0
  enable: True
- name: Loopback0
  ip: 10.255.255.31/32
  enable: True
CE2-oob.lab.local:
- name: Ethernet1/0
  enable: True
- name: Loopback0
  ip: 10.255.255.32/32
  enable: True
