3: enxb2aaccddeeff: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether b2:aa:cc:dd:ee:ff brd ff:ff:ff:ff:ff:ff
    inet 192.0.2.3/28 brd 192.0.2.15 scope global dynamic noprefixroute enxb2aaccddeeff
       valid_lft 71002sec preferred_lft 71002sec
    inet6 2001:db8:1:2:9f83:1407:723b:dc23/64 scope global temporary dynamic 
       valid_lft 604536sec preferred_lft 86009sec
    inet6 2001:db8:1:2:de:d14e:df1d:2197/64 scope global mngtmpaddr noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 2001:db8:2:3:4313:b191:1c13:715c/64 scope global temporary deprecated dynamic 
       valid_lft 6936sec preferred_lft 0sec
    inet6 2001:db8:2:3:ec7b:5c94:12d2:7409/64 scope global deprecated dynamic mngtmpaddr noprefixroute 
       valid_lft 6936sec preferred_lft 0sec
    inet6 fe80::a49f:192c:cdf8:8fb3/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
