ip ospf name-lookup
interface Ethernet0
 ip address 198.51.100.47/31
 ip ospf 4711 area 51
interface Ethernet1
 ip address 192.51.100.11/31
 ip ospf 4711 area 51
interface Ethernet2
 ip address 203.0.113.2/24
 ip ospf 4711 area 51
 vrrp 2 priority 250
 vrrp 2 ip 203.0.113.1
interface Loopback0
 ip address 192.0.2.42
 ip ospf 4711 area 51
router ospf 4711
 router-id 192.0.2.42
 passive-interface default
 no passive-interface Ethernet0
 no passive-interface Ethernet1
