!
# This file is patterned after widely used router configuration files,
# but not intended to actually work on any existing router.  Used with
# different patterns and option to provide more realistic test cases.
!
hostname router42
!
ip domain name example
ip name-server 192.0.2.13
ip ospf name-lookup
!
interface Ethernet0
 description IPv4-only transit network
 ip address 198.51.100.47/31
 ip ospf 4711 area 51
!
interface Ethernet1
 description IPv4-only transit network
 ip address 192.51.100.11/31
 ip ospf 4711 area 51
!
 description local endsystems (dual-stack)
 ip address 203.0.113.2/24
 ip ospf 4711 area 51
 vrrp 1 priority 250
 vrrp 2 priority 250
 vrrp 2 ip 203.0.113.1
!
 description BGP peering
 ip address 192.0.2.0/31
!
 description IPv6-only transit network
!
 ip address 192.0.2.42/32
 ip ospf 4711 area 51
!
router ospf 4711
 router-id 192.0.2.42
 passive-interface default
 no passive-interface Ethernet0
 no passive-interface Ethernet1
!
router ospfv3 4711
 router-id 192.0.2.42
 passive-interface default
 no passive-interface Ethernet4
!
 router-id 192.0.2.42
 no bgp default ipv4-unicast
 neighbor 192.0.2.1 remote-as 64497
 neighbor 2001:db8::1 remote-as 64498
 !
 address-family ipv4 unicast
  neighbor 192.0.2.1 activate
  network 198.51.100.0/24
 exit-address-family
 !
 exit-address-family
!
