!
# This file is patterned after widely used router configuration files,
# but not intended to actually work on any existing router.  Used with
# different patterns and option to provide more realistic test cases.
!
hostname router42
!
ip domain name example
ip name-server 192.0.2.13
ipv6 name-server 2001:db8:4711::13
!
!
!
!
interface Ethernet3
 description BGP peering
 ip address 192.0.2.0/31
 ipv6 address 2001:db8::42/64
!
!
!
!
!
router bgp 64496
 router-id 192.0.2.42
 no bgp default ipv4-unicast
 neighbor 192.0.2.1 remote-as 64497
 neighbor 2001:db8::1 remote-as 64498
 !
 address-family ipv4 unicast
  neighbor 192.0.2.1 activate
  network 198.51.100.0/24
 exit-address-family
 !
 exit-address-family
!
ipv6 route 2001:db8:5009::/64 Null0
