router bgp 64496
 router-id 192.0.2.42
 no bgp default ipv4-unicast
 neighbor 192.0.2.1 remote-as 64497
 neighbor 2001:db8::1 remote-as 64498
 !
 address-family ipv4 unicast
  neighbor 192.0.2.1 activate
  network 198.51.100.0/24
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor 2001:db8::1 activate
  network 2001:db8:5009::/64
  redistribute ospfv3 4711
 exit-address-family
!
ipv6 route 2001:db8:5009::/64 Null0
