ipv6 name-server 2001:db8:4711::13
ipv6 ospfv3 name-lookup
interface Ethernet2
 description local endsystems (dual-stack)
 ip address 203.0.113.2/24
 ipv6 address 2001:db8:113::a/64
 ipv6 address fe80::1 link-local
 ip ospf 4711 area 51
 ipv6 ospfv3 4711 area 51
 vrrp 1 priority 250
 vrrp 1 ipv6 2001:db8:113::1
 vrrp 1 ipv6 fe80::1 link-local
 vrrp 2 priority 250
 vrrp 2 ip 203.0.113.1
interface Ethernet3
 description BGP peering
 ip address 192.0.2.0/31
 ipv6 address 2001:db8::42/64
interface Ethernet4
 description IPv6-only transit network
 ipv6 address 2001:db8:2::42/64
 ipv6 ospfv3 4711 area 51
interface Loopback0
 ip address 192.0.2.42/32
 ipv6 address 2001:db8:1::42/128
 ip ospf 4711 area 51
 ipv6 ospfv3 4711 area 51
router bgp 64496
 router-id 192.0.2.42
 no bgp default ipv4-unicast
 neighbor 192.0.2.1 remote-as 64497
 neighbor 2001:db8::1 remote-as 64498
 !
 address-family ipv4 unicast
  neighbor 192.0.2.1 activate
  network 198.51.100.0/24
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor 2001:db8::1 activate
  network 2001:db8:5009::/64
  redistribute ospfv3 4711
 exit-address-family
ipv6 route 2001:db8:5009::/64 Null0
