!
# This file is patterned after widely used router configuration files,
# but not intended to actually work on any existing router.  Used with
# different patterns and option to provide more realistic test cases.
!
hostname router42
!
ip domain name example
ip name-server 192.0.2.13
ip ospf name-lookup
!
interface Ethernet0
 description IPv4-only transit network
 ip address 198.51.100.47/31
 ip ospf 4711 area 51
!
interface Ethernet1
 description IPv4-only transit network
 ip address 192.51.100.11/31
 ip ospf 4711 area 51
!
!
!
!
!
router ospf 4711
 router-id 192.0.2.42
 passive-interface default
 no passive-interface Ethernet0
 no passive-interface Ethernet1
!
router ospfv3 4711
 router-id 192.0.2.42
 passive-interface default
 no passive-interface Ethernet4
!
!
